services:
  moto:
    image: motoserver/moto:5.2.2@sha256:d8ae5edc2bf080e7e4c13f9bd4b29b53ac3b4427e92956318db3dbe23ec43eb7
    command: [-p, '4566', -H, 0.0.0.0]
    environment:
      - TZ=UTC
    ports:
      - 4566:4566
  processor:
    image: mail/processor:latest
    build:
      context: .
      dockerfile: docker/processor/Dockerfile
    ports:
      - 9001:8080
    extra_hosts:
      - localhost:host-gateway
  imapfilter:
    image: mail/imapfilter:latest
    build:
      context: .
      dockerfile: docker/imapfilter/Dockerfile
    ports:
      - 9002:8080
    extra_hosts:
      - localhost:host-gateway
