services:
  moto:
    image: motoserver/moto:5.1.22@sha256:1e3802c95726373544967b428201c548f0247c15b00db2d96a5ba0a77d8643b8
    command: [-p, '4566', -H, 0.0.0.0]
    environment:
      - TZ=UTC
    ports:
      - 4566:4566
  processor:
    image: mail/processor:latest
    build:
      context: .
      dockerfile: docker/processor/Dockerfile
    ports:
      - 9001:8080
    extra_hosts:
      - localhost:host-gateway
  imapfilter:
    image: mail/imapfilter:latest
    build:
      context: .
      dockerfile: docker/imapfilter/Dockerfile
    ports:
      - 9002:8080
    extra_hosts:
      - localhost:host-gateway
