services:
  moto:
    image: motoserver/moto:5.2.0@sha256:d8d063e3e704d256cbe8165072fa273c17698be91311e49fc602b7716f459bea
    command: [-p, '4566', -H, 0.0.0.0]
    environment:
      - TZ=UTC
    ports:
      - 4566:4566
  processor:
    image: mail/processor:latest
    build:
      context: .
      dockerfile: docker/processor/Dockerfile
    ports:
      - 9001:8080
    extra_hosts:
      - localhost:host-gateway
  imapfilter:
    image: mail/imapfilter:latest
    build:
      context: .
      dockerfile: docker/imapfilter/Dockerfile
    ports:
      - 9002:8080
    extra_hosts:
      - localhost:host-gateway
